linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - dupl
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - predeclared
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    shadow: true
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
